docker-deploy/web-app/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),


]

docker-deploy/web-app/user/urls.py
from django.urls import path
from django.contrib.auth import views as login
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('login/',views.login,name='login'),
    path('creataccount/',views.creataccount,name='creataccount'),
    path('main/',views.main,name='main'),
    path('logout/',views.logout,name='logout'),
    path('DriverReg/',views.DriverReg,name='DriverReg'),
    path('DriverEdit/',views.DriverEdit,name='DriverEdit'),
    path('ViewInfo/',views.ViewInfo,name='ViewInfo'),
    path('EditInfo/',views.EditInfo,name='EditInfo'),
    path('RideReq/',views.RideReq,name='RideReq'),
    path('<int:nid>/EditOrder/',views.EditOrder,name='EditOrder'),
    path('FindDrive/',views.FindDrive,name='FindDrive'),
    path('<int:nid>/BeDriver/',views.BeDriver,name='BeDriver'),
    path('ViewDrive/',views.ViewDrive,name='ViewDrive'),
    path('<int:nid>/Complete/',views.Complete,name='Complete'),
    path('History/',views.History,name='History'),
    path('Join/',views.Join,name='Join'),
    path('<int:nid>/JoinIt/',views.JoinIt,name='JoinIt'),
    path('ViewOwner/',views.ViewOwner,name='ViewOwner'),
    path('ViewSharer/',views.ViewSharer,name='ViewSharer'),
]

docker-deploy/web-app/user/models.py
from datetime import datetime, timezone
from django.core.validators import MinValueValidator,MaxValueValidator
from django.db import models

TypeOfVehicle = {
        ('SUV','SUV'),
        ('Sedan','Sedan'),
        ('Sports Car','Sports Car'),
    }
# Create your models here.
class User(models.Model):
    gender = {
        ('male','male'),
        ('female','female'),
        ('unknown','unknown'),
    }
    id = models.BigAutoField(primary_key=True)
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=32)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=64,choices=gender, default="unknown")
    is_driver = models.BooleanField(default=False,null=True,blank=True)
    full_name = models.CharField(max_length=32,null=True,blank=True)
    vehicle_type = models.CharField(max_length=64,choices=TypeOfVehicle,default="Sedan")
    plate_num = models.CharField(max_length=16,null=True,blank=True)
    max_passenger = models.IntegerField(validators=[
            MinValueValidator(1),MaxValueValidator(10)
        ],null=True,blank=True)
    special_vehicle_info = models.CharField(max_length=128,null=True,blank=True,default="None")
    def __str__(self):
        return self.username
class Order(models.Model):
    id = models.BigAutoField(primary_key=True)
    destination = models.CharField(max_length=128)
    arrival_time = models.DateTimeField()
    passenger_number = models.IntegerField(validators=[
        MinValueValidator(1),MaxValueValidator(10)
    ])
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner', blank=True, null=True)
    driver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='driver', blank=True,null=True)
    is_shared = models.BooleanField(default=False)
    sharer = models.ManyToManyField(User, related_name="sharer", blank=True)
    is_comfirmed=models.BooleanField(default=False)
    special_request = models.CharField(max_length=128, blank=True, default='None')
    special_vehicle_type = models.CharField(max_length=128, blank=True, default='')
    completed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

docker-deploy/web-app/user/views.py
from django.core.mail import send_mail
from django.core.validators import MinValueValidator, MaxValueValidator
from django.shortcuts import render, get_object_or_404
from django import forms

from mysite import settings
from user import models
from django.shortcuts import render, HttpResponse, redirect

from user.models import User, Order

TypeOfVehicle = {
        ('SUV','SUV'),
        ('Sedan','Sedan'),
        ('Sports Car','Sports Car'),
    }
class SharerSearchForm(forms.Form):
    destination = forms.CharField(label="destination", max_length=128,
                                  widget=forms.TextInput(attrs={'class': 'form-control'}))
    earliest_time = forms.DateTimeField(
        label="earliest time",
        input_formats=['%m/%d/%y %H:%M'],
        widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control'},
            format='%m/%d/%y %H:%M'))
    latest_time = forms.DateTimeField(
        label="latest time",
        input_formats=['%m/%d/%y %H:%M'],
        widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control'},
            format='%m/%d/%y %H:%M'))
    passenger_number = forms.IntegerField(label="passenger number", validators=[
        MinValueValidator(1), MaxValueValidator(10)
    ])


class OwnerRideForm(forms.Form):

    destination = forms.CharField(label="destination", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    arrival_time = forms.DateTimeField(label="arrival time",
    input_formats = ['%m/%d/%y %H:%M'],
        widget = forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control'},
            format='%m/%d/%y %H:%M'))
    passenger_number = forms.IntegerField(label="passenger number",validators=[
            MinValueValidator(1), MaxValueValidator(10)
        ])
    CHOICES = [('False', 'False'),('True', 'True')]
    is_shared = forms.BooleanField()
    special_request = forms.CharField(label="special request", max_length=128, required = False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    special_vehicle_type = forms.CharField(label="special vehicle type", max_length=128,required = False, widget=forms.TextInput(attrs={'class': 'form-control'}))

class OwnerModelForm(forms.ModelForm):
    class Meta:
        model=models.Order
        fields=['destination','arrival_time','passenger_number','is_shared','special_request','special_vehicle_type']
        widgets = {'arrival_time': forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control'},
            format='%m/%d/%y %H:%M')}

class ShareModelForm(forms.ModelForm):
    class Meta:
        model=models.Order
        fields=['passenger_number']
class OrderModelForm(forms.ModelForm):
    class Meta:
        model=models.Order
        fields=['destination','arrival_time','passenger_number','is_shared','special_request','special_vehicle_type']
        widgets = {'arrival_time': forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control'},
            format='%m/%d/%y %H:%M')}
class UserModelFormDriver(forms.ModelForm):
    class Meta:
        model=models.User
        fields=['username','email','sex','full_name','vehicle_type','plate_num','max_passenger','special_vehicle_info']
class UserModelFormNotDriver(forms.ModelForm):
    class Meta:
        model=models.User
        fields=['username','email','sex']


class DriverModelForm(forms.ModelForm):
    class Meta:
        model=models.User
        fields=['full_name','vehicle_type','plate_num','max_passenger','special_vehicle_info']

class LoginForm(forms.Form):
    username=forms.CharField(label="Username",widget=forms.TextInput,required=True)
    password = forms.CharField(label="password",widget=forms.PasswordInput,required=True)

class LoginModelForm(forms.ModelForm):
    class Meta:
        model=models.User
        fields=['username','password','email']

# Create your views here.
def welcome(request):
    info=request.session.get("info")
    if info:
        return redirect('/main/')
    return render(request, 'welcome.html')

def login(request):
    if request.method =="GET":
        form=LoginForm()
        return render(request,'login.html',{'form':form})
    form=LoginForm(data=request.POST)
    if form.is_valid():
        info_object = models.User.objects.filter(**form.cleaned_data).first()
        if not info_object:
            form.add_error("password", "There is something wrong with your Username or Password!")
            return render(request,'login.html',{'form':form})

        request.session["info"] = {'id': info_object.id, 'name': info_object.username}
        request.session['user_id'] = info_object.id
        request.session.set_expiry(60 * 60 * 24)
        return redirect('/main/')
    else:
        return render(request,'login.html',{'form':form})


def creataccount(request):
    if request.method =="GET":
        form=LoginModelForm()
        return render(request,'creataccount.html',{'form':form})
    form = LoginModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/login/')
    return render(request, 'creataccount.html', {'form': form})

def main(request):
    user_id = request.session.get('user_id')
    user = get_object_or_404(User, pk=user_id)
    orders = Order.objects.filter(completed=False).order_by("id")

    return render(request,'main.html',locals())
def ViewOwner(request):
    user_id = request.session.get('user_id')
    user = get_object_or_404(User, pk=user_id)
    orders=Order.objects.filter(owner__username=user.username).order_by("id")

    return render(request,'ViewOwner.html',locals())


def ViewSharer(request):
    user_id = request.session.get('user_id')
    user = get_object_or_404(User, pk=user_id)
    All = Order.objects.order_by("id")
    orders=[]
    for temporder in All.all():
        for tempshare in temporder.sharer.all():
            if tempshare.username==user.username:
                orders.append(temporder)
                break
    return render(request, 'ViewSharer.html', locals())
def EditOrder(request, nid):
    user_id = request.session.get('user_id')
    user = get_object_or_404(User, pk=user_id)
    row_object=Order.objects.filter(id=nid).first()
    mark = False
    for temp in row_object.sharer.all():
        if temp.username == user.username:
            mark = True
    if request.method=="GET":
        if row_object.is_comfirmed:
            message = "You cannot edit this order! It has been comfirmed!"
            user_id = request.session.get('user_id')
            user = get_object_or_404(User, pk=user_id)
            orders = Order.objects.filter(completed=False).order_by("id")
            return render(request, 'main.html', locals())

        if row_object.owner.username!=user.username and not mark :
            message = "You cannot edit this order!"
            user_id = request.session.get('user_id')
            user = get_object_or_404(User, pk=user_id)
            orders = Order.objects.filter(completed=False).order_by("id")
            return render(request, 'main.html', locals())
        elif row_object.owner.username==user.username:
            open_ride_form = OrderModelForm(instance=row_object)
            return render(request, 'EditOrder.html', locals())
        elif mark:
            return render(request,'ShareEdit.html')
    if request.method == 'POST':
        if mark and row_object.owner.username!=user.username:
            AddPassenger=int (request.POST.get("passenger"))

            Order.objects.filter(id=nid).update(passenger_number=row_object.passenger_number+AddPassenger)
            return redirect('/main/')
        open_ride_form = OrderModelForm(data=request.POST,instance=row_object)
        message = "please check the input!"
        if open_ride_form.is_valid():
            open_ride_form.save()
            return redirect('/main/')
        return render(request, 'EditOrder.html', locals())



def DriverReg(request):
    user_id = request.session.get('user_id')
    user = get_object_or_404(User, pk=user_id)
    if request.method=="GET":
        if user.is_driver:
            message = "You are a driver right now!"
            user_id = request.session.get('user_id')
            user = get_object_or_404(User, pk=user_id)
            orders = Order.objects.filter(completed=False).order_by("id")
            return render(request, 'main.html', locals())
        driver_form = DriverModelForm(instance=user)
        return render(request, 'DriverReg.html', locals())

    if request.method == 'POST':
        driver_form=DriverModelForm(request.POST,instance=user)
        print("s")
        if driver_form.is_valid():
            driver_form.save()
            user.is_driver=True
            user.save()
            return redirect('/main/')
        message="invalid input!"
        return render(request, 'DriverReg.html', locals())

# condsider to use modelform to edit
def DriverEdit(request):
    user_id = request.session.get('user_id')
    user = get_object_or_404(User, pk=user_id)
    if user.is_driver==False:
        return redirect('/DriverReg/')
    if request.method == 'POST':
        driver_form = DriverModelForm(request.POST,instance=user)
        message = "please check the input!"
        if driver_form.is_valid():
            driver_form.save()
            return redirect('/main/')
        return render(request, 'DriverEdit.html', locals())
    driver_form = DriverModelForm(instance=user)
    return render(request, 'DriverEdit.html', locals())

def ViewInfo(request):
    user_id = request.session.get('user_id')
    user = get_object_or_404(User, pk=user_id)
    return render(request,'ViewInfo.html',locals())

def EditInfo(request):

docker-deploy/web-app/user/templates/DriverEdit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">

    <title>driver_edit</title>
</head>
<body>
<h1>Driver Information</h1>
<div class="container">
    <div class="panel-body">
        <form class="form-driver" action="/DriverEdit/" method="post">

          {% csrf_token %}
          {% if message %}
            <div class="alert alert-warning">{{ message }}</div>
          {% endif %}

          <h3 class="text-center">Now register as a driver!</h3>

          <div class="form-group">
              {{ driver_form.full_name.label_tag }}
              {{ driver_form.full_name}}
          </div>
          <div class="form-group">
              {{ driver_form.vehicle_type.label_tag }}
              {{ driver_form.vehicle_type }}
          </div>
          <div class="form-group">
              {{ driver_form.plate_num.label_tag }}
              {{ driver_form.plate_num }}
          </div>
          <div class="form-group">
              {{ driver_form.max_passenger.label_tag }}
              <p>max:10</p>
              {{ driver_form.max_passenger }}
          </div>
          <div class="form-group">
              {{ driver_form.special_vehicle_info.label_tag }} if no special, leave it blank
              {{ driver_form.special_vehicle_info }}
          </div>

          <div>
              <button type="submit" class="btn btn-primary float-right">Edit</button>

          </div>
        </form>
        <a class="btn btn-primary" href={% url 'user:main'%} role="button">Back to Main Page</a>
    </div>
</div> <!-- /container -->


</body>
</html>

docker-deploy/web-app/user/templates/EditInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit User Info</title>
</head>
<body>
        <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Edit User </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in ChangeModel %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
<a class="btn btn-primary" href={% url 'user:main'%} role="button">Back to Main Page</a>
</body>
</html>

docker-deploy/web-app/user/templates/EditOrder.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">

    <title>Edit Order</title>
</head>
<body>
{% if message %}
            <div class="alert alert-warning">{{ message }}</div>
          {% endif %}
<div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Please edit the selected order </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        {{ open_ride_form.destination.label_tag }}
                        {{ open_ride_form.destination}}
                    </div>

                    <div class="form-group">
                        {{ open_ride_form.arrival_time.label_tag }} U.S. East time:
                        {{ open_ride_form.arrival_time }}
                    </div>

                    <div class="form-group">
                        {{ open_ride_form.passenger_number.label_tag }} between 1 - 10.
                        {{ open_ride_form.passenger_number }}
                    </div>

                    <div class="form-group">
                        {{ open_ride_form.is_shared.label_tag }}
                        {{ open_ride_form.is_shared }}
                    </div>


                    <div class="form-group">
                        {{ open_ride_form.special_request.label_tag }}
                        {{ open_ride_form.special_request }}

                    </div>

                    <div class="form-group">
                        {{ open_ride_form.special_vehicle_type.label_tag }}
                        {{ open_ride_form.special_vehicle_type }}
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                <a class="btn btn-primary" href={% url 'user:main'%} role="button">Back to Main Page</a>
            </div>
        </div>
    </div>


</body>
</html>

docker-deploy/web-app/user/templates/FindDrive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Find a Drive</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>
<div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                All available requests
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Owner</th>
                    <th>Destination</th>
                    <th>Arrival Time</th>
                    <th>Passenger Number</th>
                    <th>Share Or Not</th>
                    <th>Special Request</th>
                    <th>Special Vehicle Type</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in orders %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.owner.username }}</td>
                        <td>{{ obj.destination }}</td>
                        <td>{{ obj.arrival_time }}</td>
                        <td>{{ obj.passenger_number }}</td>
                        <td>{{ obj.is_shared }}</td>
                        {% if not obj.special_request %}
                            <td>No</td>
                        {% else %}
                            <td>{{ obj.special_request }}</td>
                        {% endif %}
                        {% if not obj.special_vehicle_type %}
                            <td>No</td>
                        {% else %}
                            <td>{{ obj.special_vehicle_type }}</td>
                        {% endif %}
                        <td>
                            <a class="btn btn-primary btn-xs" href="/{{ obj.id }}/BeDriver/">Select</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>

        </div>

    </div>
<a class="btn btn-primary" href={% url 'user:main'%} role="button">Back to Main Page</a>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

docker-deploy/web-app/user/templates/History.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Find a Drive</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>
<div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                All available requests
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Owner</th>
                    <th>Destination</th>
                    <th>Arrival Time</th>
                    <th>Passenger Number</th>
                    <th>Share Or Not</th>
                    <th>Special Request</th>
                    <th>Special Vehicle Type</th>
                    <th>Completed or Not</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in orders %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.owner.username }}</td>
                        <td>{{ obj.destination }}</td>
                        <td>{{ obj.arrival_time }}</td>
                        <td>{{ obj.passenger_number }}</td>
                        <td>{{ obj.is_shared }}</td>
                        {% if not obj.special_request %}
                            <td>No</td>
                        {% else %}
                            <td>{{ obj.special_request }}</td>
                        {% endif %}
                        {% if not obj.special_vehicle_type %}
                            <td>No</td>
                        {% else %}
                            <td>{{ obj.special_vehicle_type }}</td>
                        {% endif %}
                        <td>{{ obj.completed }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>

        </div>

    </div>
<a class="btn btn-primary" href={% url 'user:main'%} role="button">Back to Main Page</a>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

docker-deploy/web-app/user/templates/ShowAvailable.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Choose a Ride</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>
<div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                Choose a Ride
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Destintion</th>
                    <th>Time</th>
                    <th>Passenge Number</th>
                    <th>Rider Name</th>
                    <th>Special Request</th>
                    <th>Special Vehicle Type</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in target %}
                    <tr>
                        <td>{{ obj.destination }}</td>
                        <td>{{ obj.arrival_time }}</td>
                        <td>{{ obj.passenger_number }}</td>
                        <td>{{ obj.owner.username }}</td>
                        {% if not obj.special_request %}
                            <td>No</td>
                        {% else %}
                            <td>{{ obj.special_request }}</td>
                        {% endif %}
                        {% if not obj.special_vehicle_type %}
                            <td>No</td>
                        {% else %}
                            <td>{{ obj.special_vehicle_type }}</td>
                        {% endif %}
                        <td>
                            <a class="btn btn-primary btn-xs" href="/{{ obj.id }}/JoinIt/">Join</a>
                        </td>
                    </tr>

                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>

        </div>

    </div>
<a class="btn btn-primary" href={% url 'user:main'%} role="button">Back to Main Page</a>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

docker-deploy/web-app/user/templates/ViewDrive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View your Drives</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>
<div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                View your ongoing order
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Owner</th>
                    <th>Destination</th>
                    <th>Arrival Time</th>
                    <th>Passenger Number</th>
                    <th>Share Or Not</th>
                    <th>Special Request</th>
                    <th>Special Vehicle Type</th>

                </tr>
                </thead>
                <tbody>
                {% for obj in orders %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.owner.username }}</td>
                        <td>{{ obj.destination }}</td>
                        <td>{{ obj.arrival_time }}</td>
                        <td>{{ obj.passenger_number }}</td>
                        <td>{{ obj.is_shared }}</td>
                        {% if not obj.special_request %}
                            <td>No</td>
                        {% else %}
                            <td>{{ obj.special_request }}</td>
                        {% endif %}
                        {% if not obj.special_vehicle_type %}
                            <td>No</td>
                        {% else %}
                            <td>{{ obj.special_vehicle_type }}</td>
                        {% endif %}
                        <td>
                            <a class="btn btn-primary btn-xs" href="/{{ obj.id }}/Complete/">Complete</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>

        </div>

    </div>
<a class="btn btn-primary" href={% url 'user:main'%} role="button">Back to Main Page</a>
<a class="btn btn-primary" href={% url 'user:History'%} role="button">View your Drive History</a>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

docker-deploy/web-app/user/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>Login</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>Username</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>Password</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>

        <input type="submit" value="Login" class="btn btn-primary">
        <a class="btn btn-primary" href={% url 'user:creataccount'%} role="button">Creat Account</a>
        <a class="btn btn-primary" href={% url 'user:welcome'%} role="button">Back to Main Page</a>
    </form>
</div>


</body>
</html>

docker-deploy/web-app/user/templates/welcome.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>David Y ride sharing system</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">

  </head>
  <body>
  <div class="jumbotron">
  <h1>Welcome to the mini ride sharing system!</h1>
  <p>Designed by David and Joey, Durham.</p>
      <p>Now login to your own account!</p>
  <p><a class="btn btn-primary btn-lg" href={% url 'user:login'%} role="button">Login</a></p>
  </div>
  </body>
</html>